//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomersPOC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        public int customerId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<int> districtId { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    }
}
